/**
 * MCP Prompt: implement_auth
 * Step-by-step guide to implement authentication
 * @module prompts/implement-auth
 */

import { z } from 'zod';

import type { TemplateService } from '../services/template-service.js';

/**
 * Prompt arguments
 */
export interface ImplementAuthArgs {
  provider: string;
  framework: string;
  features?: string;
}

/**
 * Mapping of providers to template IDs
 */
const PROVIDER_TEMPLATE_MAP: Record<string, Record<string, string>> = {
  nextjs: {
    google: 'typescript/nextjs/auth/nextauth-google',
    credentials: 'typescript/nextjs/auth/nextauth-credentials',
    supabase: 'typescript/nextjs/auth/supabase-auth',
  },
};

/**
 * Find the appropriate auth template for given provider and framework
 */
export function findAuthTemplate(provider: string, framework: string): string | null {
  const frameworkTemplates = PROVIDER_TEMPLATE_MAP[framework.toLowerCase()];
  if (!frameworkTemplates) {
    return null;
  }

  return frameworkTemplates[provider.toLowerCase()] || null;
}

/**
 * Generate auth implementation guide
 */
export async function generateAuthGuide(
  args: ImplementAuthArgs,
  templateService: TemplateService
): Promise<string> {
  const templateId = findAuthTemplate(args.provider, args.framework);

  if (!templateId) {
    return `# Authentication Implementation Guide

## Error
No template found for provider "${args.provider}" with framework "${args.framework}".

### Available Providers by Framework

**Next.js:**
- google (NextAuth.js with Google OAuth)
- credentials (NextAuth.js with email/password)
- supabase (Supabase Auth)

Please try again with one of the available combinations.`;
  }

  const template = await templateService.getTemplateWithCode(templateId);

  if (!template) {
    return `# Authentication Implementation Guide

## Error
Template "${templateId}" not found. Please check if the template exists.`;
  }

  const guide = `# ${template.name} Implementation Guide

## Overview
${template.description}

## Step 1: Install Dependencies

\`\`\`bash
${template.usage.installation}
\`\`\`

## Step 2: Configure Environment Variables

Add the following to your \`.env\` or \`.env.local\` file:

\`\`\`env
${template.envVariables.map((env) => `# ${env.description}${env.required ? ' (required)' : ' (optional)'}
${env.name}=${env.example || 'your-value-here'}`).join('\n\n')}
\`\`\`

## Step 3: Add Code Files

${template.files.map((file) => `### ${file.path}
${file.description}
${file.isRequired ? '**Required**' : '*Optional*'}`).join('\n\n')}

## Step 4: Configuration

${template.usage.configuration}

## Step 5: Usage Example

\`\`\`typescript
${template.usage.example}
\`\`\`

${args.features ? `## Additional Features: ${args.features}

For additional features like ${args.features}, you may need to:
1. Check the related templates for extended functionality
2. Implement custom middleware or hooks
3. Extend the base authentication configuration

Related templates:
${template.relatedTemplates?.map((t) => `- ${t}`).join('\n') || '- None specified'}` : ''}

## Code Files

${Object.entries(template.code).map(([path, content]) => `### ${path}

\`\`\`typescript
${content}
\`\`\``).join('\n\n')}

---

*Generated by vibe-templates-mcp*`;

  return guide;
}

/**
 * Schema for prompt arguments
 */
export const implementAuthArgsSchema = z.object({
  provider: z.string().describe('Authentication provider (google, credentials, supabase)'),
  framework: z.string().describe('Your framework (nextjs)'),
  features: z.string().optional().describe('Additional features needed (2fa, session-management, role-based-access)'),
});

/**
 * Prompt definition for MCP
 */
export const IMPLEMENT_AUTH_PROMPT = {
  name: 'implement_auth',
  description: 'Step-by-step guide to implement authentication in your project',
  argsSchema: implementAuthArgsSchema,
};
